
# SINTAXIS BASICA DE PYTHON, IDENTACION 
if True:
    print("Este bloque esta identado correctamente")
    print("Hola davicito!!!!!")
    
# COMENTARIOS SIMPLES Y MULTIPLES

# ESTE ES UN COMENTARIO SIMPLE USANDO EL SIGNO NUMERAL

''''ESTE ES UN COMENTARIO 
    EN MULTIPLES LINEAS
    USANDO COMILLAS SIMPLES'''

"""ESTE ES UN COMENTARIO
   EN MULTIPLES LINEAS
   USANDO COMILLAS DOBLES
   PARA HACER EL COMENTARIO"""